#!/usr/bin/env bash
# adapters/ollama.sh — FableLayer Ollama Modelfile generator.
# Reads the canonical transferable procedure from core/promptcore.md and emits an
# Ollama Modelfile whose SYSTEM block injects that procedure into a local base model.
#
# What this does: injects PROCEDURE (verification grounding, evidence gate, systematic
# investigation, early-stop prevention, structured output). What it does NOT do: transfer
# model capability. A small local model gains discipline, not raw reasoning depth.
#
# Usage:
#   adapters/ollama.sh <base_model> [out_file]
#   adapters/ollama.sh llama3.1 ./out/Modelfile.fablelayer
#
# Exit codes (fail-closed):
#   0 = Modelfile written
#   2 = core/promptcore.md missing (procedure not synthesized — reported, not invented)
#   3 = usage / write error
#
# macOS bash 3.2 safe: no associative arrays, no `${arr[@]}` on possibly-empty arrays,
# byte-safe reads (no locale-dependent text processing of the procedure body).
set -u

PROG="$(basename "$0")"

usage() {
  cat <<EOF
usage: $PROG <base_model> [out_file]

  <base_model>   Ollama base model tag to build on (e.g. llama3.1, qwen2.5, mistral).
  [out_file]     Output Modelfile path. Default: ./Modelfile.fablelayer

Generates an Ollama Modelfile that injects the FableLayer transferable procedure
(from core/promptcore.md) into the base model's SYSTEM block.

Build it with:  ollama create fablelayer-<base> -f <out_file>
EOF
}

# ---- arg parsing -----------------------------------------------------------
if [ "$#" -lt 1 ]; then
  usage >&2
  exit 3
fi
case "$1" in
  -h|--help|help)
    usage
    exit 0
    ;;
esac

BASE_MODEL="$1"
OUT_FILE="${2:-./Modelfile.fablelayer}"

# ---- locate canonical procedure (core/promptcore.md) -----------------------
# Resolve repo root from this script's location so the generator works from any cwd.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
CORE="$REPO_ROOT/core/promptcore.md"

if [ ! -f "$CORE" ]; then
  echo "FAIL(2): core/promptcore.md not found at: $CORE" >&2
  echo "         The procedure is not synthesized here. Generate Layer 1 first." >&2
  exit 2
fi
if [ ! -r "$CORE" ]; then
  echo "FAIL(2): core/promptcore.md exists but is not readable: $CORE" >&2
  exit 2
fi

# ---- prepare output dir -----------------------------------------------------
OUT_DIR="$(dirname "$OUT_FILE")"
if [ ! -d "$OUT_DIR" ]; then
  mkdir -p "$OUT_DIR" || { echo "FAIL(3): cannot create output dir: $OUT_DIR" >&2; exit 3; }
fi

# ---- build SYSTEM body from the canonical procedure ------------------------
# Ollama Modelfile multi-line strings are wrapped in triple quotes. To keep the
# procedure body verbatim and avoid quote collisions, normalize any triple-quote
# sequence in the source (defensive; the canonical file should not contain them).
SAFE_BODY="$(mktemp)" || { echo "FAIL(3): mktemp failed" >&2; exit 3; }
trap 'rm -f "$SAFE_BODY"' EXIT

# Replace a literal triple-double-quote run if present, byte-safe.
sed 's/"""/\xe2\x80\x9c\xe2\x80\x9c\xe2\x80\x9c/g' "$CORE" > "$SAFE_BODY" \
  || { echo "FAIL(3): failed to read procedure body" >&2; exit 3; }

# ---- emit Modelfile --------------------------------------------------------
# Parameters are conservative defaults for procedure-following on local models.
# They tune sampling, not capability. Adjust per base model as needed.
{
  printf '# Modelfile generated by FableLayer adapters/ollama.sh\n'
  printf '# Base model: %s\n' "$BASE_MODEL"
  printf '# Injected procedure source: core/promptcore.md (transferable layer only)\n'
  printf '# Note: this injects PROCEDURE, not capability. See adapters/README.md.\n'
  printf '\n'
  printf 'FROM %s\n' "$BASE_MODEL"
  printf '\n'
  printf '# Sampling parameters: tuned for disciplined, deterministic procedure-following.\n'
  printf 'PARAMETER temperature 0.3\n'
  printf 'PARAMETER top_p 0.9\n'
  printf 'PARAMETER repeat_penalty 1.1\n'
  printf 'PARAMETER num_ctx 8192\n'
  printf '\n'
  printf 'SYSTEM """\n'
  cat "$SAFE_BODY"
  printf '\n"""\n'
} > "$OUT_FILE" || { echo "FAIL(3): cannot write $OUT_FILE" >&2; exit 3; }

echo "WROTE $OUT_FILE"
echo "base_model=$BASE_MODEL  procedure_source=$CORE"
echo "next: ollama create fablelayer-$BASE_MODEL -f $OUT_FILE"
exit 0
